### ISSUE TITLE
Add support to `UnauthorizedException`

### ISSUE THREAD

**Issue by luizhlelis** [isaacnborges/custom-exception-middleware#7]
I need to use the middleware returning a custom error message with `Unauthorized` status code. With [custom exception](https://github.com/isaacnborges/custom-exception-middleware/blob/3c5e557941987f4ebfb735928500321084be46f4/src/CustomExceptionMiddleware.cs#L74), I'm able to create a new exception and the middleware understands it, but the status code customization is not available.

I'm gonna open a PR to support `UnauthorizedException`, please check my changes and look if it makes sense 🐿

**Comment by isaacnborges** [comment]
Add support to `UnauthorizedException` in this [PR](https://github.com/isaacnborges/custom-exception-middleware/pull/9)
